export const realFixtures = [
  { match: "France vs Northern Ireland", sport: "football", odds: 1.15, strength: 8.7, volatility: 1.2, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Colombia vs Jordan", sport: "football", odds: 1.25, strength: 8.0, volatility: 1.8, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Netherlands vs Uzbekistan", sport: "football", odds: 1.30, strength: 7.7, volatility: 2.0, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Peru vs Spain", sport: "football", odds: 1.50, strength: 6.7, volatility: 3.5, outcome: "Away Win", actualResult: "Away Win" },
  { match: "Argentina vs Honduras", sport: "football", odds: 1.08, strength: 9.3, volatility: 1.0, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Afghanistan vs Pakistan", sport: "football", odds: 2.10, strength: 4.8, volatility: 5.2, outcome: "Home Win", actualResult: "Away Win" },
  { match: "Kenya vs Lesotho", sport: "football", odds: 1.65, strength: 6.1, volatility: 3.2, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Denmark vs Ukraine", sport: "football", odds: 2.10, strength: 4.8, volatility: 5.0, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Croatia vs Slovenia", sport: "football", odds: 1.60, strength: 6.3, volatility: 3.0, outcome: "Home Win", actualResult: "Home Win" },
  { match: "USA vs Germany", sport: "football", odds: 2.35, strength: 4.3, volatility: 5.5, outcome: "Away Win", actualResult: "Away Win" },
  { match: "Brazil vs Egypt", sport: "football", odds: 1.33, strength: 7.5, volatility: 2.2, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Switzerland vs Australia", sport: "football", odds: 2.00, strength: 5.0, volatility: 4.8, outcome: "Home Win", actualResult: "Draw" },
  { match: "France vs Cote dIvoire", sport: "football", odds: 1.40, strength: 7.1, volatility: 2.8, outcome: "Home Win", actualResult: "Away Win" },
  { match: "Spain vs Iraq", sport: "football", odds: 1.12, strength: 8.9, volatility: 1.1, outcome: "Home Win", actualResult: "Draw" },
  { match: "Netherlands vs Algeria", sport: "football", odds: 1.55, strength: 6.5, volatility: 3.3, outcome: "Home Win", actualResult: "Away Win" },
  { match: "Croatia vs Belgium", sport: "football", odds: 2.65, strength: 3.8, volatility: 6.0, outcome: "Away Win", actualResult: "Away Win" },
  { match: "Arsenal vs Crystal Palace", sport: "football", odds: 1.25, strength: 8.0, volatility: 1.8, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Manchester City vs Aston Villa", sport: "football", odds: 1.35, strength: 7.4, volatility: 2.3, outcome: "Home Win", actualResult: "Away Win" },
  { match: "Sunderland vs Chelsea", sport: "football", odds: 1.78, strength: 5.6, volatility: 4.2, outcome: "Away Win", actualResult: "Home Win" },
  { match: "Liverpool vs Brentford", sport: "football", odds: 1.40, strength: 7.1, volatility: 2.5, outcome: "Home Win", actualResult: "Draw" },
  { match: "Inter Miami CF vs Philadelphia Union", sport: "football", odds: 1.75, strength: 5.7, volatility: 4.0, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Columbus Crew vs Atlanta United FC", sport: "football", odds: 1.65, strength: 6.1, volatility: 3.5, outcome: "Home Win", actualResult: "Home Win" },
  { match: "Sporting Kansas City vs New York Red Bulls", sport: "football", odds: 2.45, strength: 4.1, volatility: 5.8, outcome: "Home Win", actualResult: "Away Win" },
  { match: "Portland Timbers vs San Jose Earthquakes", sport: "football", odds: 1.90, strength: 5.3, volatility: 4.5, outcome: "Home Win", actualResult: "Away Win" },
  { match: "VPS Vaasa vs HJK Helsinki", sport: "football", odds: 2.15, strength: 4.7, volatility: 5.3, outcome: "Away Win", actualResult: "Home Win" }
]
